# Use root/example as user/password credentials
version: '3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./data:/data
    working_dir: /app
    restart: always

    environment:
      NODE_ENV: development
      GIT_REPO: "https://"
      GIT_REPO_NAME: "xxxxxx"
      BUILD_ACCESS_TOKEN: "xxxxx"
      URL_PATH_PREFIX: "/marva-manual"
      PATH_TO_MENU_TEMPLATE: "menu-breadcrumbs.md"
    
    # development settings
    # environment:
    #   NODE_ENV: development
    #   URL_PATH_PREFIX: "/marva-manual"
    #   GIT_REPO_NAME: "temp-git-test"
    #   PATH_TO_MENU_TEMPLATE: "menu-breadcrumbs.md"



    ports:
      - 6565:6565
    command: npm run dev